// ═══════════════════════════════════════════════════════════════
// GRAN CANARIA CONECTA - Constants & Configuration
// Single source of truth for categories, icons, and app config
// ═══════════════════════════════════════════════════════════════

import type { DynamicField, TranslationString } from './types';

// ─────────────────────────────────────────────────────────────
// APP CONFIGURATION
// ─────────────────────────────────────────────────────────────

export const APP_CONFIG = {
  name: 'Gran Canaria Conecta',
  tagline: { es: 'Tu isla, tu comunidad, tu futuro', en: 'Your island, your community, your future' },
  description: {
    es: 'Portal comunitario de Gran Canaria. Anuncios, eventos, noticias y servicios locales con enfoque en sostenibilidad y economía circular.',
    en: 'Gran Canaria community portal. Classifieds, events, news and local services with a focus on sustainability and circular economy.',
  },
  defaultLocale: 'es' as const,
  supportedLocales: ['es', 'en'] as const,
  itemsPerPage: 12,
  featuredItemsCount: 10,
  maxListingImages: 15,
  maxFileSize: 5 * 1024 * 1024, // 5MB
  acceptedImageTypes: ['image/jpeg', 'image/png', 'image/webp', 'image/gif'],
} as const;

// ─────────────────────────────────────────────────────────────
// SITE URLS
// ─────────────────────────────────────────────────────────────

export const SITE_URLS = {
  instagram: 'https://instagram.com/granCanariaConecta',
  facebook: 'https://facebook.com/granCanariaConecta',
  twitter: 'https://twitter.com/gcConecta',
  whatsapp: 'https://wa.me/34XXXXXXXXX',
  email: 'info@grancanariaconecta.com',
} as const;

// ─────────────────────────────────────────────────────────────
// CATEGORY SEED DATA
// Organized hierarchically. Parent categories have parentId: null.
// ═══════════════════════════════════════════════════════════════

interface CategorySeed {
  slug: string;
  nameEs: string;
  nameEn: string;
  descEs?: string;
  descEn?: string;
  icon: string;
  color: string;
  parentId?: string;
  sortOrder: number;
  isPaid?: boolean;
  price?: number;
  highlightPrice?: number;
  vipPrice?: number;
  allowedFields?: DynamicField[];
  showPrice?: boolean;
  showLocation?: boolean;
  showImages?: boolean;
  maxImages?: number;
  expiryDays?: number;
}

export const CATEGORY_SEED: CategorySeed[] = [
  // ═══════════════════════════════════════════════════════════
  // 1. ECONOMÍA CIRCULAR (sortOrder: 1)
  // ═══════════════════════════════════════════════════════════
  {
    slug: 'economia-circular',
    nameEs: 'Economía Circular',
    nameEn: 'Circular Economy',
    descEs: 'Regalo, intercambio y reutilización de objetos',
    descEn: 'Giveaway, exchange and reuse of items',
    icon: 'recycle',
    color: '#52B788',
    sortOrder: 1,
  },
  {
    slug: 'regalo-intercambio',
    nameEs: 'Regalo e Intercambio',
    nameEn: 'Freecycle & Trade',
    descEs: 'Cosas gratis o para intercambiar',
    descEn: 'Free items or trade',
    icon: 'gift',
    color: '#52B788',
    parentId: 'economia-circular',
    sortOrder: 1,
    showPrice: false,
    allowedFields: [
      { key: 'condition', type: 'select', labelEs: 'Estado', labelEn: 'Condition', options: ['nuevo', 'usado', 'regular'], required: true },
    ],
  },
  {
    slug: 'materiales-construccion',
    nameEs: 'Materiales de Construcción',
    nameEn: 'Building Materials',
    descEs: 'Materiales reciclados o sobrantes de obra',
    descEn: 'Recycled or leftover building materials',
    icon: 'hammer',
    color: '#52B788',
    parentId: 'economia-circular',
    sortOrder: 2,
    allowedFields: [
      { key: 'condition', type: 'select', labelEs: 'Estado', labelEn: 'Condition', options: ['nuevo', 'usado', 'regular'], required: true },
      { key: 'quantity', type: 'text', labelEs: 'Cantidad', labelEn: 'Quantity' },
    ],
  },
  {
    slug: 'muebles-hogar',
    nameEs: 'Muebles y Hogar',
    nameEn: 'Furniture & Home',
    descEs: 'Muebles, decoración y artículos del hogar',
    descEn: 'Furniture, decoration and home items',
    icon: 'armchair',
    color: '#52B788',
    parentId: 'economia-circular',
    sortOrder: 3,
    allowedFields: [
      { key: 'condition', type: 'select', labelEs: 'Estado', labelEn: 'Condition', options: ['nuevo', 'usado', 'regular', 'para restaurar'], required: true },
      { key: 'dimensions', type: 'text', labelEs: 'Dimensiones', labelEn: 'Dimensions' },
      { key: 'material', type: 'text', labelEs: 'Material', labelEn: 'Material' },
    ],
  },
  {
    slug: 'ropa-accesorios',
    nameEs: 'Ropa y Accesorios',
    nameEn: 'Clothing & Accessories',
    descEs: 'Ropa, calzado y accesorios de segunda mano',
    descEn: 'Second-hand clothing, shoes and accessories',
    icon: 'shirt',
    color: '#52B788',
    parentId: 'economia-circular',
    sortOrder: 4,
    allowedFields: [
      { key: 'condition', type: 'select', labelEs: 'Estado', labelEn: 'Condition', options: ['nuevo', 'casi nuevo', 'usado'], required: true },
      { key: 'size', type: 'text', labelEs: 'Talla', labelEn: 'Size' },
    ],
  },
  {
    slug: 'electronica',
    nameEs: 'Electrónica',
    nameEn: 'Electronics & Devices',
    descEs: 'Dispositivos, aparatos y componentes electrónicos',
    descEn: 'Devices, appliances and electronic components',
    icon: 'smartphone',
    color: '#52B788',
    parentId: 'economia-circular',
    sortOrder: 5,
    allowedFields: [
      { key: 'condition', type: 'select', labelEs: 'Estado', labelEn: 'Condition', options: ['nuevo', 'casi nuevo', 'usado', 'para piezas'], required: true },
      { key: 'brand', type: 'text', labelEs: 'Marca', labelEn: 'Brand' },
    ],
  },
  {
    slug: 'bicicletas',
    nameEs: 'Bicicletas y eBikes',
    nameEn: 'Bicycles & eBikes',
    descEs: 'Bicis, eBikes, piezas y accesorios',
    descEn: 'Bikes, eBikes, parts and accessories',
    icon: 'bike',
    color: '#52B788',
    parentId: 'economia-circular',
    sortOrder: 6,
    allowedFields: [
      { key: 'condition', type: 'select', labelEs: 'Estado', labelEn: 'Condition', options: ['nuevo', 'usado', 'para reparar'], required: true },
      { key: 'bikeType', type: 'select', labelEs: 'Tipo', labelEn: 'Type', options: ['urbana', 'montaña', 'carretera', 'plegable', 'eléctrica'] },
      { key: 'size', type: 'text', labelEs: 'Talla', labelEn: 'Size' },
    ],
  },
  {
    slug: 'libros',
    nameEs: 'Libros y Literatura',
    nameEn: 'Books & Literature',
    descEs: 'Libros, revistas y material educativo',
    descEn: 'Books, magazines and educational material',
    icon: 'book-open',
    color: '#52B788',
    parentId: 'economia-circular',
    sortOrder: 7,
    allowedFields: [
      { key: 'condition', type: 'select', labelEs: 'Estado', labelEn: 'Condition', options: ['nuevo', 'como nuevo', 'usado'], required: true },
      { key: 'genre', type: 'text', labelEs: 'Género', labelEn: 'Genre' },
    ],
  },
  {
    slug: 'juguetes-juegos',
    nameEs: 'Juguetes y Juegos',
    nameEn: 'Toys & Games',
    descEs: 'Juguetes, juegos de mesa y deportivos',
    descEn: 'Toys, board games and sports',
    icon: 'gamepad-2',
    color: '#52B788',
    parentId: 'economia-circular',
    sortOrder: 8,
    allowedFields: [
      { key: 'condition', type: 'select', labelEs: 'Estado', labelEn: 'Condition', options: ['nuevo', 'usado'], required: true },
      { key: 'ageRange', type: 'text', labelEs: 'Rango de edad', labelEn: 'Age range' },
    ],
  },
  {
    slug: 'herramientas',
    nameEs: 'Herramientas',
    nameEn: 'Tools & Hardware',
    descEs: 'Herramientas de mano, eléctricas y de jardín',
    descEn: 'Hand tools, power tools and garden equipment',
    icon: 'wrench',
    color: '#52B788',
    parentId: 'economia-circular',
    sortOrder: 9,
    allowedFields: [
      { key: 'condition', type: 'select', labelEs: 'Estado', labelEn: 'Condition', options: ['nuevo', 'usado'], required: true },
    ],
  },
  {
    slug: 'deportes-outdoor',
    nameEs: 'Deportes y Outdoor',
    nameEn: 'Sports & Outdoor Equipment',
    descEs: 'Material deportivo, surf, senderismo y más',
    descEn: 'Sports gear, surfing, hiking and more',
    icon: 'mountain',
    color: '#52B788',
    parentId: 'economia-circular',
    sortOrder: 10,
    allowedFields: [
      { key: 'condition', type: 'select', labelEs: 'Estado', labelEn: 'Condition', options: ['nuevo', 'usado'], required: true },
      { key: 'sportType', type: 'text', labelEs: 'Deporte', labelEn: 'Sport' },
    ],
  },
  {
    slug: 'musica-instrumentos',
    nameEs: 'Música e Instrumentos',
    nameEn: 'Music & Instruments',
    descEs: 'Instrumentos, discos y equipo de audio',
    descEn: 'Instruments, records and audio equipment',
    icon: 'music',
    color: '#52B788',
    parentId: 'economia-circular',
    sortOrder: 11,
    allowedFields: [
      { key: 'condition', type: 'select', labelEs: 'Estado', labelEn: 'Condition', options: ['nuevo', 'usado'], required: true },
      { key: 'instrumentType', type: 'text', labelEs: 'Tipo de instrumento', labelEn: 'Instrument type' },
    ],
  },
  {
    slug: 'artesania-arte',
    nameEs: 'Artesanía y Arte',
    nameEn: 'Arts & Crafts',
    descEs: 'Material artístico, manualidades y artesanía local',
    descEn: 'Art supplies, crafts and local artisan work',
    icon: 'palette',
    color: '#52B788',
    parentId: 'economia-circular',
    sortOrder: 12,
    allowedFields: [
      { key: 'condition', type: 'select', labelEs: 'Estado', labelEn: 'Condition', options: ['nuevo', 'usado'], required: true },
      { key: 'craftType', type: 'text', labelEs: 'Tipo de artesanía', labelEn: 'Craft type' },
    ],
  },
  {
    slug: 'trasteros-talleres',
    nameEs: 'Trasteros y Talleres',
    nameEn: 'Storage & Workshops',
    descEs: 'Trasteros, garajes y talleres en alquiler o cesión',
    descEn: 'Storage units, garages and workshops for rent or share',
    icon: 'warehouse',
    color: '#52B788',
    parentId: 'economia-circular',
    sortOrder: 13,
    allowedFields: [
      { key: 'storageType', type: 'select', labelEs: 'Tipo', labelEn: 'Type', options: ['trastero', 'garaje', 'taller', 'navaja'], required: true },
      { key: 'area', type: 'number', labelEs: 'Superficie m²', labelEn: 'Area m²' },
    ],
  },
  {
    slug: 'pequenos-anuncios',
    nameEs: 'Pequeños Anuncios',
    nameEn: 'General Items',
    descEs: 'Otros artículos que no encajan en las categorías anteriores',
    descEn: 'Other items that don\'t fit in the above categories',
    icon: 'package',
    color: '#52B788',
    parentId: 'economia-circular',
    sortOrder: 14,
    allowedFields: [
      { key: 'condition', type: 'select', labelEs: 'Estado', labelEn: 'Condition', options: ['nuevo', 'usado'], required: true },
    ],
  },

  // ═══════════════════════════════════════════════════════════
  // 2. VEHÍCULOS (sortOrder: 2)
  // ═══════════════════════════════════════════════════════════
  {
    slug: 'vehiculos',
    nameEs: 'Vehículos',
    nameEn: 'Vehicles',
    descEs: 'Coches, motos, embarcaciones y maquinaria',
    descEn: 'Cars, motorcycles, boats and machinery',
    icon: 'car',
    color: '#1D3557',
    sortOrder: 2,
    allowedFields: [
      { key: 'condition', type: 'select', labelEs: 'Estado', labelEn: 'Condition', options: ['nuevo', 'seminuevo', 'usado', 'para piezas'], required: true },
      { key: 'brand', type: 'text', labelEs: 'Marca', labelEn: 'Brand', required: true },
      { key: 'model', type: 'text', labelEs: 'Modelo', labelEn: 'Model', required: true },
      { key: 'year', type: 'number', labelEs: 'Año', labelEn: 'Year', min: 1900, max: 2030 },
      { key: 'fuel', type: 'select', labelEs: 'Combustible', labelEn: 'Fuel', options: ['gasolina', 'diésel', 'eléctrico', 'híbrido', 'GLP'] },
      { key: 'km', type: 'number', labelEs: 'Kilómetros', labelEn: 'Kilometers' },
    ],
    maxImages: 10,
    expiryDays: 60,
  },
  {
    slug: 'coches-furgonetas',
    nameEs: 'Coches y Furgonetas',
    nameEn: 'Cars & Trucks: For Sale',
    descEs: 'Turismos, SUVs, furgonetas y comerciales',
    descEn: 'Sedans, SUVs, vans and commercial vehicles',
    icon: 'car',
    color: '#1D3557',
    parentId: 'vehiculos',
    sortOrder: 1,
    allowedFields: [
      { key: 'condition', type: 'select', labelEs: 'Estado', labelEn: 'Condition', options: ['nuevo', 'seminuevo', 'usado', 'para piezas'], required: true },
      { key: 'brand', type: 'text', labelEs: 'Marca', labelEn: 'Brand', required: true },
      { key: 'model', type: 'text', labelEs: 'Modelo', labelEn: 'Model', required: true },
      { key: 'year', type: 'number', labelEs: 'Año', labelEn: 'Year', min: 1900, max: 2030 },
      { key: 'fuel', type: 'select', labelEs: 'Combustible', labelEn: 'Fuel', options: ['gasolina', 'diésel', 'eléctrico', 'híbrido', 'GLP'] },
      { key: 'km', type: 'number', labelEs: 'Kilómetros', labelEn: 'Kilometers' },
    ],
    maxImages: 10,
    expiryDays: 60,
  },
  {
    slug: 'coches-piezas',
    nameEs: 'Coches: Piezas',
    nameEn: 'Cars & Trucks: Parts',
    descEs: 'Recambios, piezas y accesorios para coches',
    descEn: 'Spare parts and accessories for cars and trucks',
    icon: 'wrench',
    color: '#1D3557',
    parentId: 'vehiculos',
    sortOrder: 2,
    allowedFields: [
      { key: 'condition', type: 'select', labelEs: 'Estado', labelEn: 'Condition', options: ['nuevo', 'usado', 'reconstruido'], required: true },
      { key: 'brand', type: 'text', labelEs: 'Marca del vehículo', labelEn: 'Vehicle brand' },
      { key: 'partType', type: 'text', labelEs: 'Tipo de pieza', labelEn: 'Part type', required: true },
    ],
    expiryDays: 60,
  },
  {
    slug: 'motos-scooters',
    nameEs: 'Motos y Scooters',
    nameEn: 'Motorcycles & Scooters: For Sale',
    descEs: 'Motos, scooters, quads y ciclomotores',
    descEn: 'Motorcycles, scooters, quads and mopeds',
    icon: 'bike',
    color: '#1D3557',
    parentId: 'vehiculos',
    sortOrder: 3,
    allowedFields: [
      { key: 'condition', type: 'select', labelEs: 'Estado', labelEn: 'Condition', options: ['nuevo', 'seminuevo', 'usado', 'para piezas'], required: true },
      { key: 'brand', type: 'text', labelEs: 'Marca', labelEn: 'Brand', required: true },
      { key: 'model', type: 'text', labelEs: 'Modelo', labelEn: 'Model', required: true },
      { key: 'year', type: 'number', labelEs: 'Año', labelEn: 'Year', min: 1990, max: 2030 },
      { key: 'cc', type: 'number', labelEs: 'Cilindrada (cc)', labelEn: 'Engine capacity (cc)' },
      { key: 'km', type: 'number', labelEs: 'Kilómetros', labelEn: 'Kilometers' },
    ],
    maxImages: 10,
    expiryDays: 60,
  },
  {
    slug: 'motos-piezas',
    nameEs: 'Motos: Piezas',
    nameEn: 'Motorcycles & Scooters: Parts',
    descEs: 'Recambios y accesorios para motos y scooters',
    descEn: 'Spare parts and accessories for motorcycles and scooters',
    icon: 'wrench',
    color: '#1D3557',
    parentId: 'vehiculos',
    sortOrder: 4,
    allowedFields: [
      { key: 'condition', type: 'select', labelEs: 'Estado', labelEn: 'Condition', options: ['nuevo', 'usado', 'reconstruido'], required: true },
      { key: 'brand', type: 'text', labelEs: 'Marca', labelEn: 'Brand' },
      { key: 'partType', type: 'text', labelEs: 'Tipo de pieza', labelEn: 'Part type', required: true },
    ],
    expiryDays: 60,
  },
  {
    slug: 'embarcaciones-venta',
    nameEs: 'Embarcaciones: Venta',
    nameEn: 'Boats, Trailers & RVs: For Sale',
    descEs: 'Barcos, veleros, lanchas, remolques y autocaravanas',
    descEn: 'Boats, sailboats, speedboats, trailers and RVs',
    icon: 'ship',
    color: '#1D3557',
    parentId: 'vehiculos',
    sortOrder: 5,
    allowedFields: [
      { key: 'condition', type: 'select', labelEs: 'Estado', labelEn: 'Condition', options: ['nuevo', 'usado', 'para restaurar'], required: true },
      { key: 'boatType', type: 'select', labelEs: 'Tipo', labelEn: 'Type', options: ['velero', 'lancha', 'barco de pesca', 'kayak', 'paddle surf', 'remolque', 'autocaravana', 'otro'], required: true },
      { key: 'length', type: 'number', labelEs: 'Eslora (m)', labelEn: 'Length (m)' },
      { key: 'year', type: 'number', labelEs: 'Año', labelEn: 'Year', min: 1970, max: 2030 },
    ],
    maxImages: 10,
    expiryDays: 60,
  },
  {
    slug: 'embarcaciones-piezas',
    nameEs: 'Embarcaciones: Piezas',
    nameEn: 'Boats, Trailers & RVs: Parts',
    descEs: 'Recambios y accesorios náuticos',
    descEn: 'Nautical spare parts and accessories',
    icon: 'wrench',
    color: '#1D3557',
    parentId: 'vehiculos',
    sortOrder: 6,
    allowedFields: [
      { key: 'condition', type: 'select', labelEs: 'Estado', labelEn: 'Condition', options: ['nuevo', 'usado'], required: true },
      { key: 'partType', type: 'text', labelEs: 'Tipo de pieza', labelEn: 'Part type', required: true },
    ],
    expiryDays: 60,
  },
  {
    slug: 'embarcaciones-amarre',
    nameEs: 'Embarcaciones: Amarre',
    nameEn: 'Boats: Moorage for Rent or Sale',
    descEs: 'Amarres, plazas de puerto y almacenes náuticos',
    descEn: 'Mooring spots, marina berths and nautical storage',
    icon: 'anchor',
    color: '#1D3557',
    parentId: 'vehiculos',
    sortOrder: 7,
    allowedFields: [
      { key: 'mooringType', type: 'select', labelEs: 'Tipo', labelEn: 'Type', options: ['amarre', 'pantalán', 'fondeo', 'almacén náutico'], required: true },
      { key: 'length', type: 'number', labelEs: 'Eslora máxima (m)', labelEn: 'Max length (m)' },
      { key: 'services', type: 'text', labelEs: 'Servicios incluidos', labelEn: 'Included services' },
    ],
    expiryDays: 60,
  },
  {
    slug: 'maquinaria-agricola',
    nameEs: 'Maquinaria Agrícola',
    nameEn: 'Farm & Heavy Equipment',
    descEs: 'Tractores, retroexcavadoras y maquinaria pesada',
    descEn: 'Tractors, excavators and heavy machinery',
    icon: 'tractor',
    color: '#1D3557',
    parentId: 'vehiculos',
    sortOrder: 8,
    allowedFields: [
      { key: 'condition', type: 'select', labelEs: 'Estado', labelEn: 'Condition', options: ['nuevo', 'usado', 'para reparar'], required: true },
      { key: 'brand', type: 'text', labelEs: 'Marca', labelEn: 'Brand', required: true },
      { key: 'model', type: 'text', labelEs: 'Modelo', labelEn: 'Model' },
      { key: 'year', type: 'number', labelEs: 'Año', labelEn: 'Year', min: 1980, max: 2030 },
      { key: 'hours', type: 'number', labelEs: 'Horas de uso', labelEn: 'Hours of use' },
    ],
    maxImages: 10,
    expiryDays: 60,
  },

  // ═══════════════════════════════════════════════════════════
  // 3. VIVIENDA (sortOrder: 3)
  // ═══════════════════════════════════════════════════════════
  {
    slug: 'vivienda',
    nameEs: 'Vivienda',
    nameEn: 'Housing',
    descEs: 'Alquiler, venta, compartir y vacaciones',
    descEn: 'Rent, sale, flatshare and vacation rentals',
    icon: 'home',
    color: '#264653',
    sortOrder: 3,
  },
  {
    slug: 'vivienda-alquiler',
    nameEs: 'Alquiler',
    nameEn: 'Housing: For Rent',
    descEs: 'Pisos, casas, habitaciones y locales en alquiler',
    descEn: 'Apartments, houses, rooms and commercial space for rent',
    icon: 'key',
    color: '#264653',
    parentId: 'vivienda',
    sortOrder: 1,
    allowedFields: [
      { key: 'type', type: 'select', labelEs: 'Tipo', labelEn: 'Type', options: ['piso', 'casa', 'habitación', 'estudio', 'local', 'garaje'], required: true },
      { key: 'bedrooms', type: 'number', labelEs: 'Habitaciones', labelEn: 'Bedrooms', min: 0, max: 20 },
      { key: 'bathrooms', type: 'number', labelEs: 'Baños', labelEn: 'Bathrooms', min: 1, max: 10 },
      { key: 'area', type: 'number', labelEs: 'Superficie m²', labelEn: 'Area m²' },
      { key: 'furnished', type: 'boolean', labelEs: 'Amueblado', labelEn: 'Furnished' },
      { key: 'pets', type: 'boolean', labelEs: 'Admiten mascotas', labelEn: 'Pets allowed' },
      { key: 'longTerm', type: 'boolean', labelEs: 'Larga temporada', labelEn: 'Long term' },
    ],
    maxImages: 10,
    expiryDays: 60,
  },
  {
    slug: 'vivienda-venta',
    nameEs: 'Venta',
    nameEn: 'Housing: For Sale',
    descEs: 'Pisos, casas, chalets, terrenos y garajes en venta',
    descEn: 'Apartments, houses, villas, land and garages for sale',
    icon: 'building',
    color: '#264653',
    parentId: 'vivienda',
    sortOrder: 2,
    allowedFields: [
      { key: 'type', type: 'select', labelEs: 'Tipo', labelEn: 'Type', options: ['piso', 'casa', 'chalet', 'terreno', 'local', 'garaje'], required: true },
      { key: 'bedrooms', type: 'number', labelEs: 'Habitaciones', labelEn: 'Bedrooms' },
      { key: 'bathrooms', type: 'number', labelEs: 'Baños', labelEn: 'Bathrooms' },
      { key: 'area', type: 'number', labelEs: 'Superficie m²', labelEn: 'Area m²' },
      { key: 'pool', type: 'boolean', labelEs: 'Piscina', labelEn: 'Pool' },
      { key: 'garden', type: 'boolean', labelEs: 'Jardín', labelEn: 'Garden' },
      { key: 'parking', type: 'boolean', labelEs: 'Garaje', labelEn: 'Parking' },
    ],
    maxImages: 10,
    expiryDays: 60,
  },
  {
    slug: 'vivienda-compartir',
    nameEs: 'Compartir',
    nameEn: 'Flatshare & Roommates',
    descEs: 'Compartir piso, buscar compañeros o habitación',
    descEn: 'Flatsharing, find roommates or a room',
    icon: 'users',
    color: '#264653',
    parentId: 'vivienda',
    sortOrder: 3,
    allowedFields: [
      { key: 'type', type: 'select', labelEs: 'Tipo', labelEn: 'Type', options: ['busco habitación', 'ofrezco habitación', 'busco compañero/a', 'intercambio temporal'], required: true },
      { key: 'budget', type: 'number', labelEs: 'Presupuesto máximo €/mes', labelEn: 'Max budget €/month' },
      { key: 'preferences', type: 'text', labelEs: 'Preferencias', labelEn: 'Preferences' },
    ],
    expiryDays: 60,
  },
  {
    slug: 'vivienda-intercambio',
    nameEs: 'Intercambio',
    nameEn: 'Housing: Swap & Exchange',
    descEs: 'Intercambio temporal o permuta de vivienda',
    descEn: 'Temporary swap or house exchange',
    icon: 'key',
    color: '#264653',
    parentId: 'vivienda',
    sortOrder: 4,
    allowedFields: [
      { key: 'swapType', type: 'select', labelEs: 'Tipo de intercambio', labelEn: 'Swap type', options: ['temporal', 'permuta', 'intercambio por servicio'], required: true },
      { key: 'duration', type: 'text', labelEs: 'Duración', labelEn: 'Duration' },
    ],
    expiryDays: 60,
  },
  {
    slug: 'vivienda-vacaciones',
    nameEs: 'Vacaciones y Alojamientos',
    nameEn: 'Housing: Vacations & Rentals',
    descEs: 'Apartamentos turísticos, casas rurales y bnb',
    descEn: 'Tourist apartments, rural houses and B&B',
    icon: 'umbrella',
    color: '#264653',
    parentId: 'vivienda',
    sortOrder: 5,
    allowedFields: [
      { key: 'type', type: 'select', labelEs: 'Tipo', labelEn: 'Type', options: ['apartamento', 'casa', 'bungalow', 'hostal', 'otro'], required: true },
      { key: 'guests', type: 'number', labelEs: 'Capacidad (personas)', labelEn: 'Capacity (guests)', min: 1, max: 20 },
      { key: 'bedrooms', type: 'number', labelEs: 'Habitaciones', labelEn: 'Bedrooms', min: 1, max: 10 },
      { key: 'minStay', type: 'number', labelEs: 'Estancia mínima (noches)', labelEn: 'Minimum stay (nights)' },
      { key: 'pool', type: 'boolean', labelEs: 'Piscina', labelEn: 'Pool' },
      { key: 'wifi', type: 'boolean', labelEs: 'WiFi', labelEn: 'WiFi' },
    ],
    maxImages: 10,
    expiryDays: 60,
  },
  {
    slug: 'vivienda-busca',
    nameEs: 'Se Busca',
    nameEn: 'Housing: Wanted',
    descEs: 'Busco vivienda o habitación',
    descEn: 'Looking for a home or room',
    icon: 'search',
    color: '#264653',
    parentId: 'vivienda',
    sortOrder: 6,
    allowedFields: [
      { key: 'type', type: 'select', labelEs: 'Tipo buscado', labelEn: 'Type wanted', options: ['piso', 'casa', 'habitación', 'local', 'garaje'], required: true },
      { key: 'budget', type: 'number', labelEs: 'Presupuesto máximo €/mes', labelEn: 'Max budget €/month' },
      { key: 'zones', type: 'text', labelEs: 'Zonas preferidas', labelEn: 'Preferred areas' },
    ],
    showPrice: false,
    expiryDays: 60,
  },
  {
    slug: 'vivienda-prefabricadas',
    nameEs: 'Casas Prefabricadas',
    nameEn: 'Tiny Homes: For Sale',
    descEs: 'Casas prefabricadas, tiny houses y módulos',
    descEn: 'Prefabricated homes, tiny houses and modules',
    icon: 'home',
    color: '#264653',
    parentId: 'vivienda',
    sortOrder: 7,
    allowedFields: [
      { key: 'condition', type: 'select', labelEs: 'Estado', labelEn: 'Condition', options: ['nuevo', 'usado', 'por construir'], required: true },
      { key: 'area', type: 'number', labelEs: 'Superficie m²', labelEn: 'Area m²' },
      { key: 'bedrooms', type: 'number', labelEs: 'Habitaciones', labelEn: 'Bedrooms' },
      { key: 'transportable', type: 'boolean', labelEs: 'Transportable', labelEn: 'Transportable' },
    ],
    maxImages: 10,
    expiryDays: 60,
  },

  // ═══════════════════════════════════════════════════════════
  // 4. NEGOCIOS Y SERVICIOS (sortOrder: 4, PAID)
  // ═══════════════════════════════════════════════════════════
  {
    slug: 'negocios-servicios',
    nameEs: 'Negocios y Servicios',
    nameEn: 'Business & Services',
    descEs: 'Directorio de negocios y profesionales locales',
    descEn: 'Local business and professional directory',
    icon: 'store',
    color: '#7C3AED',
    sortOrder: 4,
    isPaid: true,
    price: 25,
    highlightPrice: 10,
    vipPrice: 30,
  },
  {
    slug: 'productos-servicios',
    nameEs: 'Productos y Servicios',
    nameEn: 'Business: Products & Services',
    descEs: 'Tiendas, profesionales y servicios generales',
    descEn: 'Shops, professionals and general services',
    icon: 'store',
    color: '#7C3AED',
    parentId: 'negocios-servicios',
    sortOrder: 1,
    isPaid: true,
    allowedFields: [
      { key: 'specialty', type: 'text', labelEs: 'Especialidad', labelEn: 'Specialty', required: true },
      { key: 'phone', type: 'text', labelEs: 'Teléfono', labelEn: 'Phone', required: true },
      { key: 'website', type: 'url', labelEs: 'Web', labelEn: 'Website' },
      { key: 'hours', type: 'text', labelEs: 'Horario', labelEn: 'Hours' },
    ],
    maxImages: 10,
    expiryDays: 90,
  },
  {
    slug: 'restaurantes-catering',
    nameEs: 'Restaurantes y Catering',
    nameEn: 'Food: Restaurants & Catering',
    descEs: 'Gastronomía local, restaurantes y servicios de catering',
    descEn: 'Local gastronomy, restaurants and catering services',
    icon: 'utensils',
    color: '#7C3AED',
    parentId: 'negocios-servicios',
    sortOrder: 2,
    isPaid: true,
    allowedFields: [
      { key: 'cuisine', type: 'text', labelEs: 'Tipo de cocina', labelEn: 'Cuisine type' },
      { key: 'phone', type: 'text', labelEs: 'Teléfono', labelEn: 'Phone', required: true },
      { key: 'website', type: 'url', labelEs: 'Web', labelEn: 'Website' },
      { key: 'hours', type: 'text', labelEs: 'Horario', labelEn: 'Hours' },
      { key: 'delivery', type: 'boolean', labelEs: 'Domicilio', labelEn: 'Delivery' },
      { key: 'terrace', type: 'boolean', labelEs: 'Terraza', labelEn: 'Terrace' },
      { key: 'isEco', type: 'boolean', labelEs: 'Km 0 / Ecológico', labelEn: 'Km 0 / Eco' },
    ],
    maxImages: 10,
    expiryDays: 90,
  },
  {
    slug: 'negocio-venta',
    nameEs: 'Negocio en Venta',
    nameEn: 'Business: For Sale',
    descEs: 'Traspasos, negocios en venta y franquicias',
    descEn: 'Business transfers, businesses for sale and franchises',
    icon: 'briefcase',
    color: '#7C3AED',
    parentId: 'negocios-servicios',
    sortOrder: 3,
    isPaid: true,
    allowedFields: [
      { key: 'businessType', type: 'select', labelEs: 'Tipo de negocio', labelEn: 'Business type', options: ['restauración', 'comercio', 'servicios', 'hostelería', 'otro'], required: true },
      { key: 'year', type: 'number', labelEs: 'Año de fundación', labelEn: 'Year established', min: 1950, max: 2030 },
      { key: 'area', type: 'number', labelEs: 'Superficie m²', labelEn: 'Area m²' },
      { key: 'staff', type: 'number', labelEs: 'Empleados', labelEn: 'Staff' },
      { key: 'reason', type: 'text', labelEs: 'Motivo de venta', labelEn: 'Reason for sale' },
    ],
    maxImages: 10,
    expiryDays: 90,
  },
  {
    slug: 'local-comercial-alquiler',
    nameEs: 'Local Comercial: Alquiler',
    nameEn: 'Business: Commercial Rent or Lease',
    descEs: 'Locales, naves y oficinas en alquiler',
    descEn: 'Commercial premises, warehouses and offices for rent',
    icon: 'building',
    color: '#7C3AED',
    parentId: 'negocios-servicios',
    sortOrder: 4,
    isPaid: true,
    allowedFields: [
      { key: 'propertyType', type: 'select', labelEs: 'Tipo', labelEn: 'Type', options: ['local', 'nave', 'oficina', 'solar', 'co-working'], required: true },
      { key: 'area', type: 'number', labelEs: 'Superficie m²', labelEn: 'Area m²' },
      { key: 'price', type: 'number', labelEs: 'Precio €/mes', labelEn: 'Price €/month' },
    ],
    maxImages: 10,
    expiryDays: 90,
  },
  {
    slug: 'jardineria-paisajismo',
    nameEs: 'Jardinería y Paisajismo',
    nameEn: 'Services: Gardening & Landscaping',
    descEs: 'Servicios de jardinería, diseño de paisajes y mantenimiento',
    descEn: 'Gardening, landscaping design and maintenance services',
    icon: 'flower-2',
    color: '#7C3AED',
    parentId: 'negocios-servicios',
    sortOrder: 5,
    isPaid: true,
    allowedFields: [
      { key: 'specialty', type: 'select', labelEs: 'Especialidad', labelEn: 'Specialty', options: ['jardinería', 'paisajismo', 'riego automático', 'podas', 'mantenimiento', 'diseño'], required: true },
      { key: 'phone', type: 'text', labelEs: 'Teléfono', labelEn: 'Phone', required: true },
      { key: 'website', type: 'url', labelEs: 'Web', labelEn: 'Website' },
      { key: 'hours', type: 'text', labelEs: 'Horario', labelEn: 'Hours' },
      { key: 'emergency', type: 'boolean', labelEs: 'Urgencias', labelEn: 'Emergency service' },
    ],
    expiryDays: 90,
  },
  {
    slug: 'limpieza-hogar',
    nameEs: 'Limpieza del Hogar',
    nameEn: 'Services: House Cleaning',
    descEs: 'Servicios de limpieza para el hogar y oficinas',
    descEn: 'House cleaning and office cleaning services',
    icon: 'sparkles',
    color: '#7C3AED',
    parentId: 'negocios-servicios',
    sortOrder: 6,
    isPaid: true,
    allowedFields: [
      { key: 'specialty', type: 'select', labelEs: 'Especialidad', labelEn: 'Specialty', options: ['hogar', 'oficina', 'comunidad', 'fondo de cocina', 'lavandería'], required: true },
      { key: 'phone', type: 'text', labelEs: 'Teléfono', labelEn: 'Phone', required: true },
      { key: 'hours', type: 'text', labelEs: 'Horario', labelEn: 'Hours' },
      { key: 'certified', type: 'boolean', labelEs: 'Certificado', labelEn: 'Certified' },
    ],
    expiryDays: 90,
  },
  {
    slug: 'carpinteros-oficios',
    nameEs: 'Carpinteros y Oficios',
    nameEn: 'Services: Contractors & Trades',
    descEs: 'Carpinteros, electricistas, fontaneros y oficios varios',
    descEn: 'Carpenters, electricians, plumbers and various trades',
    icon: 'wrench',
    color: '#7C3AED',
    parentId: 'negocios-servicios',
    sortOrder: 7,
    isPaid: true,
    allowedFields: [
      { key: 'specialty', type: 'select', labelEs: 'Especialidad', labelEn: 'Specialty', options: ['carpintería', 'electricidad', 'fontanería', 'albañilería', 'pintura', 'cristalería', 'soldadura', 'otro'], required: true },
      { key: 'phone', type: 'text', labelEs: 'Teléfono', labelEn: 'Phone', required: true },
      { key: 'website', type: 'url', labelEs: 'Web', labelEn: 'Website' },
      { key: 'hours', type: 'text', labelEs: 'Horario', labelEn: 'Hours' },
      { key: 'emergency', type: 'boolean', labelEs: 'Urgencias 24h', labelEn: '24h Emergency' },
      { key: 'certified', type: 'boolean', labelEs: 'Certificado', labelEn: 'Certified' },
    ],
    expiryDays: 90,
  },
  {
    slug: 'mano-obra-general',
    nameEs: 'Mano de Obra General',
    nameEn: 'Services: General Work & Labour',
    descEs: 'Ayuda general, montajes, mudanzas y trabajos puntuales',
    descEn: 'General help, assembly, moving and odd jobs',
    icon: 'hammer',
    color: '#7C3AED',
    parentId: 'negocios-servicios',
    sortOrder: 8,
    isPaid: true,
    allowedFields: [
      { key: 'specialty', type: 'text', labelEs: 'Tipo de trabajo', labelEn: 'Type of work', required: true },
      { key: 'phone', type: 'text', labelEs: 'Teléfono', labelEn: 'Phone', required: true },
      { key: 'hours', type: 'text', labelEs: 'Horario', labelEn: 'Hours' },
    ],
    expiryDays: 90,
  },
  {
    slug: 'cuidado-mayores',
    nameEs: 'Cuidado de Mayores',
    nameEn: 'Services: Seniors',
    descEs: 'Cuidados a domicilio, compañía y ayuda para personas mayores',
    descEn: 'Home care, companionship and assistance for seniors',
    icon: 'heart',
    color: '#7C3AED',
    parentId: 'negocios-servicios',
    sortOrder: 9,
    isPaid: true,
    allowedFields: [
      { key: 'specialty', type: 'select', labelEs: 'Tipo de servicio', labelEn: 'Service type', options: ['cuidado domiciliario', 'compañía', 'ayuda movilidad', 'fisioterapia', 'teleasistencia'], required: true },
      { key: 'phone', type: 'text', labelEs: 'Teléfono', labelEn: 'Phone', required: true },
      { key: 'hours', type: 'text', labelEs: 'Horario', labelEn: 'Hours' },
      { key: 'certified', type: 'boolean', labelEs: 'Certificado', labelEn: 'Certified' },
    ],
    expiryDays: 90,
  },
  {
    slug: 'cuidado-ninos',
    nameEs: 'Cuidado de Niños',
    nameEn: 'Services: Child Care & Baby Sitting',
    descEs: 'Canguros, guarderías y cuidado infantil',
    descEn: 'Babysitters, nurseries and child care',
    icon: 'baby',
    color: '#7C3AED',
    parentId: 'negocios-servicios',
    sortOrder: 10,
    isPaid: true,
    allowedFields: [
      { key: 'specialty', type: 'select', labelEs: 'Tipo de servicio', labelEn: 'Service type', options: ['canguro', 'guardería', 'aula matinal', 'actividades extraescolares'], required: true },
      { key: 'phone', type: 'text', labelEs: 'Teléfono', labelEn: 'Phone', required: true },
      { key: 'hours', type: 'text', labelEs: 'Horario', labelEn: 'Hours' },
      { key: 'certified', type: 'boolean', labelEs: 'Certificado', labelEn: 'Certified' },
    ],
    expiryDays: 90,
  },
  {
    slug: 'podadores-arboles',
    nameEs: 'Podadores y Árboles',
    nameEn: 'Services: Arborists & Tree Falling',
    descEs: 'Servicios de poda, tala y cuidado de árboles y palmeras',
    descEn: 'Pruning, felling and tree/palm care services',
    icon: 'trees',
    color: '#7C3AED',
    parentId: 'negocios-servicios',
    sortOrder: 11,
    isPaid: true,
    allowedFields: [
      { key: 'specialty', type: 'select', labelEs: 'Especialidad', labelEn: 'Specialty', options: ['poda', 'tala', 'trasplante', 'tratamiento fitosanitario', 'palmeras', 'otro'], required: true },
      { key: 'phone', type: 'text', labelEs: 'Teléfono', labelEn: 'Phone', required: true },
      { key: 'certified', type: 'boolean', labelEs: 'Certificado', labelEn: 'Certified' },
    ],
    expiryDays: 90,
  },
  {
    slug: 'mantenimiento-propiedades',
    nameEs: 'Mantenimiento de Propiedades',
    nameEn: 'Services: Property Maintenance',
    descEs: 'Administración de fincas, comunidades y mantenimiento integral',
    descEn: 'Property management, communities and comprehensive maintenance',
    icon: 'home',
    color: '#7C3AED',
    parentId: 'negocios-servicios',
    sortOrder: 12,
    isPaid: true,
    allowedFields: [
      { key: 'specialty', type: 'select', labelEs: 'Especialidad', labelEn: 'Specialty', options: ['administración de fincas', 'mantenimiento integral', 'piscinas', 'ascensores', 'limpieza de comunidades'], required: true },
      { key: 'phone', type: 'text', labelEs: 'Teléfono', labelEn: 'Phone', required: true },
      { key: 'website', type: 'url', labelEs: 'Web', labelEn: 'Website' },
      { key: 'hours', type: 'text', labelEs: 'Horario', labelEn: 'Hours' },
    ],
    expiryDays: 90,
  },

  // ═══════════════════════════════════════════════════════════
  // 5. EMPLEO (sortOrder: 5)
  // ═══════════════════════════════════════════════════════════
  {
    slug: 'empleo',
    nameEs: 'Empleo',
    nameEn: 'Jobs',
    descEs: 'Ofertas de trabajo, empleos puntuales y formación',
    descEn: 'Job opportunities, odd jobs and training',
    icon: 'briefcase',
    color: '#0D9488',
    sortOrder: 5,
  },
  {
    slug: 'ofertas-empleo',
    nameEs: 'Ofertas de Empleo',
    nameEn: 'Hiring: Employment Opportunities',
    descEs: 'Ofertas de trabajo fijas, temporales y por cuenta propia',
    descEn: 'Full-time, part-time and self-employment opportunities',
    icon: 'briefcase',
    color: '#0D9488',
    parentId: 'empleo',
    sortOrder: 1,
    allowedFields: [
      { key: 'jobType', type: 'select', labelEs: 'Tipo de contrato', labelEn: 'Contract type', options: ['fijo', 'temporal', 'autónomo', 'prácticas', 'beca'], required: true },
      { key: 'sector', type: 'text', labelEs: 'Sector', labelEn: 'Sector', required: true },
      { key: 'experience', type: 'select', labelEs: 'Experiencia', labelEn: 'Experience', options: ['sin experiencia', 'junior', 'medio', 'senior'], required: true },
      { key: 'remote', type: 'boolean', labelEs: 'Teletrabajo', labelEn: 'Remote' },
      { key: 'salary', type: 'text', labelEs: 'Salario', labelEn: 'Salary' },
    ],
    expiryDays: 90,
  },
  {
    slug: 'trabajos-puntuales',
    nameEs: 'Trabajos Puntuales',
    nameEn: 'Hiring: Odd Jobs & Helping Hands',
    descEs: 'Trabajos esporádicos, ayudantes y colaboraciones',
    descEn: 'Sporadic work, helpers and collaborations',
    icon: 'hand-helping',
    color: '#0D9488',
    parentId: 'empleo',
    sortOrder: 2,
    allowedFields: [
      { key: 'jobType', type: 'text', labelEs: 'Tipo de trabajo', labelEn: 'Job type', required: true },
      { key: 'duration', type: 'select', labelEs: 'Duración', labelEn: 'Duration', options: ['unas horas', 'un día', 'varios días', 'una semana', 'varias semanas'] },
      { key: 'experience', type: 'select', labelEs: 'Experiencia requerida', labelEn: 'Experience required', options: ['no necesaria', 'básica', 'media'] },
    ],
    expiryDays: 90,
  },
  {
    slug: 'formacion-talleres',
    nameEs: 'Formación y Talleres',
    nameEn: 'Education, Workshops & Training',
    descEs: 'Cursos, talleres y oportunidades de formación profesional',
    descEn: 'Courses, workshops and professional training opportunities',
    icon: 'graduation-cap',
    color: '#0D9488',
    parentId: 'empleo',
    sortOrder: 3,
    allowedFields: [
      { key: 'courseType', type: 'select', labelEs: 'Tipo', labelEn: 'Type', options: ['presencial', 'online', 'mixto'], required: true },
      { key: 'sector', type: 'text', labelEs: 'Sector', labelEn: 'Sector', required: true },
      { key: 'duration', type: 'text', labelEs: 'Duración', labelEn: 'Duration' },
      { key: 'certificate', type: 'boolean', labelEs: 'Con certificado', labelEn: 'With certificate' },
      { key: 'price', type: 'text', labelEs: 'Precio', labelEn: 'Price' },
    ],
    expiryDays: 90,
  },

  // ═══════════════════════════════════════════════════════════
  // 6. COMUNIDAD (sortOrder: 6)
  // ═══════════════════════════════════════════════════════════
  {
    slug: 'comunidad',
    nameEs: 'Comunidad',
    nameEn: 'Community',
    descEs: 'Vida comunitaria, mascotas, voluntariado y más',
    descEn: 'Community life, pets, volunteering and more',
    icon: 'users',
    color: '#6366F1',
    sortOrder: 6,
  },
  {
    slug: 'mascotas',
    nameEs: 'Mascotas y Animales',
    nameEn: 'Pets & Animals: General',
    descEs: 'Adopciones, mascotas perdidas y cuidados',
    descEn: 'Adoptions, lost pets and pet care',
    icon: 'paw-print',
    color: '#6366F1',
    parentId: 'comunidad',
    sortOrder: 1,
    showPrice: false,
    allowedFields: [
      { key: 'animalType', type: 'select', labelEs: 'Tipo', labelEn: 'Type', options: ['perro', 'gato', 'pájaro', 'reptil', 'pez', 'conejo', 'otro'], required: true },
      { key: 'listingType', type: 'select', labelEs: 'Tipo de anuncio', labelEn: 'Listing type', options: ['adopción', 'se perdió', 'se encontró', 'cuidador', 'accesorios', 'servicio'], required: true },
      { key: 'breed', type: 'text', labelEs: 'Raza', labelEn: 'Breed' },
      { key: 'age', type: 'text', labelEs: 'Edad', labelEn: 'Age' },
    ],
  },
  {
    slug: 'servicios-mascotas',
    nameEs: 'Servicios para Mascotas',
    nameEn: 'Pets & Animals: Sales & Services',
    descEs: 'Peluquería, veterinaria, paseadores y productos para mascotas',
    descEn: 'Pet grooming, vet, dog walkers and pet products',
    icon: 'heart',
    color: '#6366F1',
    parentId: 'comunidad',
    sortOrder: 2,
    allowedFields: [
      { key: 'animalType', type: 'select', labelEs: 'Tipo de animal', labelEn: 'Animal type', options: ['perro', 'gato', 'pájaro', 'reptil', 'pez', 'otro'], required: true },
      { key: 'serviceType', type: 'select', labelEs: 'Tipo de servicio', labelEn: 'Service type', options: ['peluquería', 'veterinario', 'paseador', 'educador', 'guardería', 'productos', 'otro'], required: true },
      { key: 'phone', type: 'text', labelEs: 'Teléfono', labelEn: 'Phone' },
      { key: 'website', type: 'url', labelEs: 'Web', labelEn: 'Website' },
      { key: 'hours', type: 'text', labelEs: 'Horario', labelEn: 'Hours' },
    ],
  },
  {
    slug: 'perdidos-encontrados',
    nameEs: 'Perdidos y Encontrados',
    nameEn: 'Lost & Found',
    descEs: 'Objetos, documentación y mascotas perdidas o encontradas',
    descEn: 'Lost or found items, documents and pets',
    icon: 'search',
    color: '#6366F1',
    parentId: 'comunidad',
    sortOrder: 3,
    showPrice: false,
    allowedFields: [
      { key: 'listingType', type: 'select', labelEs: 'Tipo', labelEn: 'Type', options: ['se perdió', 'se encontró', 'se robó'], required: true },
      { key: 'itemType', type: 'select', labelEs: 'Categoría', labelEn: 'Category', options: ['mascota', 'documentos', 'electrónica', 'ropa', 'llaves', 'vehículo', 'otro'], required: true },
      { key: 'date', type: 'date', labelEs: 'Fecha', labelEn: 'Date', required: true },
      { key: 'location', type: 'text', labelEs: 'Dónde', labelEn: 'Where' },
    ],
  },
  {
    slug: 'voluntarios',
    nameEs: 'Voluntarios',
    nameEn: 'Volunteers',
    descEs: 'Busco voluntarios / Ofrezco voluntariado',
    descEn: 'Looking for volunteers / Offering to volunteer',
    icon: 'heart-handshake',
    color: '#6366F1',
    parentId: 'comunidad',
    sortOrder: 4,
    showPrice: false,
    allowedFields: [
      { key: 'volunteerType', type: 'select', labelEs: 'Tipo', labelEn: 'Type', options: ['ambiental', 'social', 'animal', 'cultural', 'educativo', 'otro'], required: true },
      { key: 'commitment', type: 'select', labelEs: 'Compromiso', labelEn: 'Commitment', options: ['puntual', 'semanal', 'mensual', 'temporal'] },
    ],
  },
  {
    slug: 'ninos-jovenes-campamentos',
    nameEs: 'Niños y Jóvenes: Campamentos',
    nameEn: 'Kids & Youth: Camps & Events',
    descEs: 'Campamentos, colonias y actividades para niños y adolescentes',
    descEn: 'Camps, summer programs and activities for kids and teens',
    icon: 'star',
    color: '#6366F1',
    parentId: 'comunidad',
    sortOrder: 5,
    showPrice: false,
    allowedFields: [
      { key: 'ageRange', type: 'text', labelEs: 'Rango de edad', labelEn: 'Age range', required: true },
      { key: 'activityType', type: 'select', labelEs: 'Tipo', labelEn: 'Type', options: ['campamento', 'colonia', 'taller', 'deporte', 'arte', 'naturaleza', 'tecnología', 'otro'], required: true },
      { key: 'dates', type: 'text', labelEs: 'Fechas', labelEn: 'Dates' },
    ],
  },
  {
    slug: 'ninos-jovenes-general',
    nameEs: 'Niños y Jóvenes: General',
    nameEn: 'Kids & Youth: General',
    descEs: 'Anuncios relacionados con niños y jóvenes en general',
    descEn: 'General announcements related to kids and youth',
    icon: 'baby',
    color: '#6366F1',
    parentId: 'comunidad',
    sortOrder: 6,
    showPrice: false,
  },
  {
    slug: 'cuidado-hogar-mascotas',
    nameEs: 'Cuidado de Hogar y Mascotas',
    nameEn: 'House, Farm & Pet Sitting',
    descEs: 'Cuidadores de casas, fincas y mascotas mientras viajas',
    descEn: 'House, farm and pet sitters while you travel',
    icon: 'home',
    color: '#6366F1',
    parentId: 'comunidad',
    sortOrder: 7,
    showPrice: false,
    allowedFields: [
      { key: 'sittingType', type: 'select', labelEs: 'Tipo', labelEn: 'Type', options: ['casa', 'finca', 'mascotas', 'combinado'], required: true },
      { key: 'duration', type: 'text', labelEs: 'Duración', labelEn: 'Duration' },
    ],
  },
  {
    slug: 'amigos-contactos',
    nameEs: 'Amigos y Contactos',
    nameEn: 'Friends & Networking',
    descEs: 'Hacer amigos, grupos de interés y contactos en la isla',
    descEn: 'Make friends, interest groups and networking on the island',
    icon: 'message-circle',
    color: '#6366F1',
    parentId: 'comunidad',
    sortOrder: 8,
    showPrice: false,
    allowedFields: [
      { key: 'interest', type: 'text', labelEs: 'Intereses', labelEn: 'Interests' },
      { key: 'age', type: 'text', labelEs: 'Rango de edad', labelEn: 'Age range' },
    ],
  },
  {
    slug: 'compartir-viajes',
    nameEs: 'Compartir Viajes',
    nameEn: 'Rideshare & Pick Ups',
    descEs: 'Compartir coche, buscar o ofrecer transporte',
    descEn: 'Carpooling, offer or request transport',
    icon: 'car',
    color: '#6366F1',
    parentId: 'comunidad',
    sortOrder: 9,
    showPrice: false,
    allowedFields: [
      { key: 'routeType', type: 'select', labelEs: 'Tipo', labelEn: 'Type', options: ['ofrezco viaje', 'busco viaje', 'compartir gastos'], required: true },
      { key: 'origin', type: 'text', labelEs: 'Origen', labelEn: 'Origin', required: true },
      { key: 'destination', type: 'text', labelEs: 'Destino', labelEn: 'Destination', required: true },
      { key: 'schedule', type: 'text', labelEs: 'Horario / Frecuencia', labelEn: 'Schedule / Frequency' },
    ],
  },
  {
    slug: 'discusion-opiniones',
    nameEs: 'Discusión y Opiniones',
    nameEn: 'Discussion & Opinions',
    descEs: 'Debate, opiniones y conversación sobre temas locales',
    descEn: 'Discussion, opinions and local topics conversation',
    icon: 'megaphone',
    color: '#6366F1',
    parentId: 'comunidad',
    sortOrder: 10,
    showPrice: false,
  },
  {
    slug: 'preguntas-recomendaciones',
    nameEs: 'Preguntas y Recomendaciones',
    nameEn: 'Questions & Recommendations',
    descEs: 'Pregunta a la comunidad o recomienda algo',
    descEn: 'Ask the community or recommend something',
    icon: 'message-circle',
    color: '#6366F1',
    parentId: 'comunidad',
    sortOrder: 11,
    showPrice: false,
  },
  {
    slug: 'noticias-comunitarias',
    nameEs: 'Noticias Comunitarias',
    nameEn: 'Community News',
    descEs: 'Anuncios de interés general para la comunidad',
    descEn: 'General interest announcements for the community',
    icon: 'megaphone',
    color: '#6366F1',
    parentId: 'comunidad',
    sortOrder: 12,
    showPrice: false,
  },
  {
    slug: 'anuncios-nacimiento',
    nameEs: 'Anuncios de Nacimiento',
    nameEn: 'Birth Announcements',
    descEs: 'Comparte la llegada de un nuevo miembro de la familia',
    descEn: 'Share the arrival of a new family member',
    icon: 'baby',
    color: '#6366F1',
    parentId: 'comunidad',
    sortOrder: 13,
    showPrice: false,
  },
  {
    slug: 'necesidades-agradecimientos',
    nameEs: 'Necesidades y Agradecimientos',
    nameEn: 'Thanks & Appreciation',
    descEs: 'Da las gracias, pide ayuda o muestra agradecimiento',
    descEn: 'Give thanks, ask for help or show appreciation',
    icon: 'heart',
    color: '#6366F1',
    parentId: 'comunidad',
    sortOrder: 14,
    showPrice: false,
  },

  // ═══════════════════════════════════════════════════════════
  // 7. SALUD Y BIENESTAR (sortOrder: 7)
  // ═══════════════════════════════════════════════════════════
  {
    slug: 'salud-bienestar',
    nameEs: 'Salud y Bienestar',
    nameEn: 'Health & Wellness',
    descEs: 'Artículos de salud, movilidad, servicios y espiritualidad',
    descEn: 'Health items, mobility, services and spirituality',
    icon: 'heart-pulse',
    color: '#EC4899',
    sortOrder: 7,
  },
  {
    slug: 'articulos-salud',
    nameEs: 'Artículos de Salud',
    nameEn: 'Health & Wellness: Items',
    descEs: 'Artículos ortopédicos, médicos y de bienestar',
    descEn: 'Orthopedic, medical and wellness items',
    icon: 'heart-pulse',
    color: '#EC4899',
    parentId: 'salud-bienestar',
    sortOrder: 1,
    allowedFields: [
      { key: 'condition', type: 'select', labelEs: 'Estado', labelEn: 'Condition', options: ['nuevo', 'usado'], required: true },
      { key: 'itemType', type: 'text', labelEs: 'Tipo de artículo', labelEn: 'Item type', required: true },
    ],
  },
  {
    slug: 'movilidad-scooters',
    nameEs: 'Movilidad y Scooters',
    nameEn: 'Health & Wellness: Mobility Scooters',
    descEs: 'Sillas de ruedas, scooters de movilidad y bastones',
    descEn: 'Wheelchairs, mobility scooters and walking aids',
    icon: 'dumbbell',
    color: '#EC4899',
    parentId: 'salud-bienestar',
    sortOrder: 2,
    allowedFields: [
      { key: 'condition', type: 'select', labelEs: 'Estado', labelEn: 'Condition', options: ['nuevo', 'seminuevo', 'usado'], required: true },
      { key: 'mobilityType', type: 'select', labelEs: 'Tipo', labelEn: 'Type', options: ['silla de ruedas', 'scooter', 'andador', 'bastón', 'muletas', 'otro'], required: true },
    ],
  },
  {
    slug: 'servicios-eventos-salud',
    nameEs: 'Servicios, Eventos, Clases',
    nameEn: 'Health & Wellness: Services, Events, Classes & Retreats',
    descEs: 'Terapias, yoga, retiros y actividades de bienestar',
    descEn: 'Therapies, yoga, retreats and wellness activities',
    icon: 'sparkles',
    color: '#EC4899',
    parentId: 'salud-bienestar',
    sortOrder: 3,
    allowedFields: [
      { key: 'wellnessType', type: 'select', labelEs: 'Tipo', labelEn: 'Type', options: ['yoga', 'meditación', 'masaje', 'terapia', 'retiro', 'clase', 'taller', 'otro'], required: true },
      { key: 'phone', type: 'text', labelEs: 'Teléfono', labelEn: 'Phone' },
      { key: 'website', type: 'url', labelEs: 'Web', labelEn: 'Website' },
      { key: 'hours', type: 'text', labelEs: 'Horario', labelEn: 'Hours' },
      { key: 'homeVisit', type: 'boolean', labelEs: 'Visita a domicilio', labelEn: 'Home visit' },
    ],
  },
  {
    slug: 'espiritualidad-fe',
    nameEs: 'Espiritualidad y Fe',
    nameEn: 'Spirituality & Faith',
    descEs: 'Grupos espirituales, meditación y comunidades de fe',
    descEn: 'Spiritual groups, meditation and faith communities',
    icon: 'heart',
    color: '#EC4899',
    parentId: 'salud-bienestar',
    sortOrder: 4,
    showPrice: false,
  },

  // ═══════════════════════════════════════════════════════════
  // 8. EVENTOS (sortOrder: 8)
  // ═══════════════════════════════════════════════════════════
  {
    slug: 'eventos',
    nameEs: 'Eventos',
    nameEn: 'Events',
    descEs: 'Conciertos, encuentros, ferias y eventos comunitarios',
    descEn: 'Concerts, gatherings, fairs and community events',
    icon: 'calendar',
    color: '#EA580C',
    sortOrder: 8,
  },
  {
    slug: 'eventos-conciertos-encuentros',
    nameEs: 'Eventos, Conciertos y Encuentros',
    nameEn: 'Events, Concerts & Gatherings',
    descEs: 'Conciertos, ferias, mercadillos y eventos culturales',
    descEn: 'Concerts, fairs, markets and cultural events',
    icon: 'calendar',
    color: '#EA580C',
    parentId: 'eventos',
    sortOrder: 1,
    allowedFields: [
      { key: 'eventType', type: 'select', labelEs: 'Tipo', labelEn: 'Type', options: ['concierto', 'feria', 'mercadillo', 'exposición', 'encuentro', 'fiesta', 'otro'], required: true },
      { key: 'date', type: 'date', labelEs: 'Fecha', labelEn: 'Date', required: true },
      { key: 'time', type: 'text', labelEs: 'Hora', labelEn: 'Time' },
      { key: 'location', type: 'text', labelEs: 'Lugar', labelEn: 'Venue' },
    ],
    showPrice: false,
  },
  {
    slug: 'eventos-gratuitos',
    nameEs: 'Eventos Gratuitos',
    nameEn: 'Events: Free & by Donation',
    descEs: 'Eventos sin coste de entrada o por donación voluntaria',
    descEn: 'Events with no entrance fee or by voluntary donation',
    icon: 'star',
    color: '#EA580C',
    parentId: 'eventos',
    sortOrder: 2,
    showPrice: false,
    allowedFields: [
      { key: 'eventType', type: 'select', labelEs: 'Tipo', labelEn: 'Type', options: ['taller', 'charla', 'concierto', 'actividad infantil', 'deporte', 'naturaleza', 'otro'], required: true },
      { key: 'date', type: 'date', labelEs: 'Fecha', labelEn: 'Date', required: true },
      { key: 'time', type: 'text', labelEs: 'Hora', labelEn: 'Time' },
      { key: 'location', type: 'text', labelEs: 'Lugar', labelEn: 'Venue' },
    ],
  },

  // ═══════════════════════════════════════════════════════════
  // 9. AGRICULTURA Y GRANJAS (sortOrder: 9)
  // ═══════════════════════════════════════════════════════════
  {
    slug: 'agricultura-granjas',
    nameEs: 'Agricultura y Granjas',
    nameEn: 'Agriculture & Farms',
    descEs: 'Granjas, huertos, productos locales y animales de corral',
    descEn: 'Farms, orchards, local products and farm animals',
    icon: 'sprout',
    color: '#65A30D',
    sortOrder: 9,
  },
  {
    slug: 'granjas-huertos',
    nameEs: 'Granjas y Huertos',
    nameEn: 'Farm, Farm Stands & Gardening',
    descEs: 'Huertos urbanos, granjas ecológicas y venta directa',
    descEn: 'Urban gardens, organic farms and direct sales',
    icon: 'sprout',
    color: '#65A30D',
    parentId: 'agricultura-granjas',
    sortOrder: 1,
    allowedFields: [
      { key: 'farmType', type: 'select', labelEs: 'Tipo', labelEn: 'Type', options: ['huerto urbano', 'granja ecológica', 'huerta', 'invernadero', 'otro'], required: true },
      { key: 'products', type: 'text', labelEs: 'Productos', labelEn: 'Products' },
      { key: 'organic', type: 'boolean', labelEs: 'Ecológico', labelEn: 'Organic' },
      { key: 'phone', type: 'text', labelEs: 'Teléfono', labelEn: 'Phone' },
      { key: 'hours', type: 'text', labelEs: 'Horario', labelEn: 'Hours' },
    ],
  },
  {
    slug: 'productos-locales',
    nameEs: 'Productos Locales',
    nameEn: 'Local Products',
    descEs: 'Productos canarios: quesos, vinos, miel, gofio y más',
    descEn: 'Canarian products: cheeses, wines, honey, gofio and more',
    icon: 'coffee',
    color: '#65A30D',
    parentId: 'agricultura-granjas',
    sortOrder: 2,
    allowedFields: [
      { key: 'productType', type: 'select', labelEs: 'Tipo de producto', labelEn: 'Product type', options: ['queso', 'vino', 'miel', 'gofio', 'frutas', 'verduras', 'hierbas', 'artesanía alimentaria', 'otro'], required: true },
      { key: 'organic', type: 'boolean', labelEs: 'Ecológico', labelEn: 'Organic' },
      { key: 'denomination', type: 'boolean', labelEs: 'Denominación de origen', labelEn: 'Designation of origin' },
    ],
  },
  {
    slug: 'animales-granja',
    nameEs: 'Animales de Granja',
    nameEn: 'Farm Animals',
    descEs: 'Ganado, aves de corral y animales de granja',
    descEn: 'Livestock, poultry and farm animals',
    icon: 'leaf',
    color: '#65A30D',
    parentId: 'agricultura-granjas',
    sortOrder: 3,
    allowedFields: [
      { key: 'animalType', type: 'select', labelEs: 'Tipo', labelEn: 'Type', options: ['cabra', 'oveja', 'vaca', 'pollo', 'conejo', 'cerdo', 'caballo', 'burro', 'otro'], required: true },
      { key: 'breed', type: 'text', labelEs: 'Raza', labelEn: 'Breed' },
      { key: 'listingType', type: 'select', labelEs: 'Tipo de anuncio', labelEn: 'Listing type', options: ['venta', 'adopción', 'servicio de semental', 'intercambio'], required: true },
    ],
  },

  // ═══════════════════════════════════════════════════════════
  // 10. ARTE Y CULTURA (sortOrder: 10)
  // ═══════════════════════════════════════════════════════════
  {
    slug: 'arte-cultura',
    nameEs: 'Arte y Cultura',
    nameEn: 'Art & Culture',
    descEs: 'Exposiciones, talleres, fotografía y artes escénicas',
    descEn: 'Exhibitions, workshops, photography and performing arts',
    icon: 'palette',
    color: '#9B5DE5',
    sortOrder: 10,
  },
  {
    slug: 'exposiciones-talleres',
    nameEs: 'Exposiciones y Talleres',
    nameEn: 'Art Exhibitions & Workshops',
    descEs: 'Exposiciones de arte, talleres creativos y cursos artísticos',
    descEn: 'Art exhibitions, creative workshops and art courses',
    icon: 'palette',
    color: '#9B5DE5',
    parentId: 'arte-cultura',
    sortOrder: 1,
    allowedFields: [
      { key: 'artType', type: 'select', labelEs: 'Disciplina', labelEn: 'Discipline', options: ['pintura', 'escultura', 'cerámica', 'fotografía', 'diseño', 'grabado', 'mixta', 'otro'], required: true },
      { key: 'date', type: 'date', labelEs: 'Fecha', labelEn: 'Date' },
      { key: 'location', type: 'text', labelEs: 'Lugar', labelEn: 'Venue' },
      { key: 'price', type: 'text', labelEs: 'Precio', labelEn: 'Price' },
    ],
    showPrice: false,
  },
  {
    slug: 'fotografia',
    nameEs: 'Fotografía',
    nameEn: 'Photography',
    descEs: 'Fotografía profesional, de boda, de paisajes y talleres',
    descEn: 'Professional, wedding, landscape photography and workshops',
    icon: 'camera',
    color: '#9B5DE5',
    parentId: 'arte-cultura',
    sortOrder: 2,
    allowedFields: [
      { key: 'photoType', type: 'select', labelEs: 'Especialidad', labelEn: 'Specialty', options: ['boda', 'retrato', 'paisaje', 'producto', 'evento', 'inmobiliaria', 'otro'], required: true },
      { key: 'phone', type: 'text', labelEs: 'Teléfono', labelEn: 'Phone' },
      { key: 'website', type: 'url', labelEs: 'Web', labelEn: 'Website' },
    ],
  },
  {
    slug: 'teatro-espectaculos',
    nameEs: 'Teatro y Espectáculos',
    nameEn: 'Theater & Performing Arts',
    descEs: 'Obras de teatro, danza, monólogos y espectáculos en vivo',
    descEn: 'Theater plays, dance, stand-up comedy and live shows',
    icon: 'music',
    color: '#9B5DE5',
    parentId: 'arte-cultura',
    sortOrder: 3,
    allowedFields: [
      { key: 'showType', type: 'select', labelEs: 'Tipo', labelEn: 'Type', options: ['teatro', 'danza', 'monólogo', 'concierto', 'flamenco', 'magia', 'circo', 'otro'], required: true },
      { key: 'date', type: 'date', labelEs: 'Fecha', labelEn: 'Date', required: true },
      { key: 'time', type: 'text', labelEs: 'Hora', labelEn: 'Time' },
      { key: 'location', type: 'text', labelEs: 'Lugar', labelEn: 'Venue' },
    ],
    showPrice: false,
  },

  // ═══════════════════════════════════════════════════════════
  // 11. ANUNCIOS ESPECIALES (sortOrder: 11)
  // ═══════════════════════════════════════════════════════════
  {
    slug: 'anuncios-especiales',
    nameEs: 'Anuncios Especiales',
    nameEn: 'Special Announcements',
    descEs: 'Fundraising, ONGs, servicios gubernamentales y más',
    descEn: 'Fundraising, NGOs, government services and more',
    icon: 'megaphone',
    color: '#64748B',
    sortOrder: 11,
  },
  {
    slug: 'recaudacion-fondos',
    nameEs: 'Recaudación de Fondos',
    nameEn: 'Fundraising & Crowdsourcing',
    descEs: 'Campañas de crowdfunding, benéficas y recaudación de fondos',
    descEn: 'Crowdfunding campaigns, charity and fundraising',
    icon: 'heart-handshake',
    color: '#64748B',
    parentId: 'anuncios-especiales',
    sortOrder: 1,
    showPrice: false,
    allowedFields: [
      { key: 'fundType', type: 'select', labelEs: 'Tipo', labelEn: 'Type', options: ['médico', 'educativo', 'social', 'ambiental', 'cultural', 'emergencia', 'otro'], required: true },
      { key: 'goal', type: 'number', labelEs: 'Objetivo (€)', labelEn: 'Goal (€)' },
      { key: 'deadline', type: 'date', labelEs: 'Fecha límite', labelEn: 'Deadline' },
      { key: 'website', type: 'url', labelEs: 'Enlace de donación', labelEn: 'Donation link' },
    ],
  },
  {
    slug: 'sin-animo-lucro',
    nameEs: 'Sin ánimo de Lucro',
    nameEn: 'Non-Profit Ads (Registered)',
    descEs: 'Asociaciones y ONGs registradas sin ánimo de lucro',
    descEn: 'Registered non-profit associations and NGOs',
    icon: 'shield-check',
    color: '#64748B',
    parentId: 'anuncios-especiales',
    sortOrder: 2,
    showPrice: false,
    allowedFields: [
      { key: 'orgName', type: 'text', labelEs: 'Nombre de la organización', labelEn: 'Organization name', required: true },
      { key: 'orgType', type: 'select', labelEs: 'Tipo', labelEn: 'Type', options: ['asociación', 'fundación', 'ONG', 'cooperativa', 'otro'], required: true },
      { key: 'phone', type: 'text', labelEs: 'Teléfono', labelEn: 'Phone' },
      { key: 'website', type: 'url', labelEs: 'Web', labelEn: 'Website' },
    ],
  },
  {
    slug: 'servicios-gubernamentales',
    nameEs: 'Servicios Gubernamentales',
    nameEn: 'Government & Official Services',
    descEs: 'Información y avisos de ayuntamientos y organismos oficiales',
    descEn: 'Information and notices from municipalities and official bodies',
    icon: 'building',
    color: '#64748B',
    parentId: 'anuncios-especiales',
    sortOrder: 3,
    showPrice: false,
  },
  {
    slug: 'obituarios-recuerdos',
    nameEs: 'Obituarios y Recuerdos',
    nameEn: 'Obituaries & Remembrances',
    descEs: 'In memoriam y avisos fúnebres',
    descEn: 'In memoriam and funeral notices',
    icon: 'heart',
    color: '#64748B',
    parentId: 'anuncios-especiales',
    sortOrder: 4,
    showPrice: false,
  },
  {
    slug: 'reclamaciones-felicitaciones',
    nameEs: 'Reclamaciones y Felicitaciones',
    nameEn: 'Rants & Roses',
    descEs: 'Quejas constructivas, sugerencias y felicitaciones',
    descEn: 'Constructive complaints, suggestions and compliments',
    icon: 'megaphone',
    color: '#64748B',
    parentId: 'anuncios-especiales',
    sortOrder: 5,
    showPrice: false,
  },
  {
    slug: 'garage-sales',
    nameEs: 'Garage Sales',
    nameEn: 'Garage Sales',
    descEs: 'Mercadillos de garaje, ventas de trastero y rebajas',
    descEn: 'Garage sales, attic clearances and moving sales',
    icon: 'tag',
    color: '#64748B',
    parentId: 'anuncios-especiales',
    sortOrder: 6,
    allowedFields: [
      { key: 'saleType', type: 'select', labelEs: 'Tipo', labelEn: 'Type', options: ['garage sale', 'venta de trastero', 'traslado', 'liquidación', 'otro'], required: true },
      { key: 'date', type: 'date', labelEs: 'Fecha', labelEn: 'Date' },
      { key: 'time', type: 'text', labelEs: 'Horario', labelEn: 'Time' },
      { key: 'location', type: 'text', labelEs: 'Dirección', labelEn: 'Address' },
    ],
  },
  {
    slug: 'se-busca-especial',
    nameEs: 'Se Busca',
    nameEn: 'Wanted',
    descEs: 'Busco algo específico que no encuentro en otras categorías',
    descEn: 'Looking for something specific not found in other categories',
    icon: 'search',
    color: '#64748B',
    parentId: 'anuncios-especiales',
    sortOrder: 7,
    showPrice: false,
    allowedFields: [
      { key: 'category', type: 'text', labelEs: '¿Qué buscas?', labelEn: 'What are you looking for?', required: true },
    ],
  },

  // ═══════════════════════════════════════════════════════════
  // 12. CLASIFICADOS PREMIUM (sortOrder: 12, PAID)
  // ═══════════════════════════════════════════════════════════
  {
    slug: 'clasificados-premium',
    nameEs: 'Clasificados Premium',
    nameEn: 'Premium Classifieds',
    descEs: 'Anuncios destacados con máxima visibilidad',
    descEn: 'Featured ads with maximum visibility',
    icon: 'crown',
    color: '#D97706',
    sortOrder: 12,
    isPaid: true,
    price: 25,
    highlightPrice: 10,
    vipPrice: 30,
  },
  {
    slug: 'anuncios-destacados',
    nameEs: 'Anuncios Destacados',
    nameEn: 'Featured Classifieds',
    descEs: 'Publica tu anuncio con visibilidad premium en toda la plataforma',
    descEn: 'Publish your ad with premium visibility across the platform',
    icon: 'star',
    color: '#D97706',
    parentId: 'clasificados-premium',
    sortOrder: 1,
    isPaid: true,
    maxImages: 15,
  },
];

// ─────────────────────────────────────────────────────────────
// NAVIGATION CONFIGURATION
// ─────────────────────────────────────────────────────────────

export const NAV_ITEMS: TranslationString[] = [
  { es: 'Anuncios', en: 'Classifieds' },
  { es: 'Categorías', en: 'Categories' },
  { es: 'Eventos', en: 'Events' },
  { es: 'Noticias', en: 'News' },
  { es: 'Directorio', en: 'Directory' },
  { es: 'Reciclaje', en: 'Recycling' },
];

// ─────────────────────────────────────────────────────────────
// FOOTER LINKS
// ─────────────────────────────────────────────────────────────

export const FOOTER_LINKS = {
  about: [
    { es: 'Sobre nosotros', en: 'About us' },
    { es: 'Contacto', en: 'Contact' },
    { es: 'Cómo funciona', en: 'How it works' },
    { es: 'Precios', en: 'Pricing' },
  ],
  resources: [
    { es: 'Puntos de reciclaje', en: 'Recycling points' },
    { es: 'Guía eco', en: 'Eco guide' },
    { es: 'Transporte', en: 'Transport' },
    { es: 'Clima y playas', en: 'Weather & beaches' },
  ],
  legal: [
    { es: 'Términos de uso', en: 'Terms of use' },
    { es: 'Privacidad', en: 'Privacy' },
    { es: 'Cookies', en: 'Cookies' },
    { es: 'Aviso legal', en: 'Legal notice' },
  ],
};

// ─────────────────────────────────────────────────────────────
// EVENT CATEGORIES
// ─────────────────────────────────────────────────────────────

export const EVENT_CATEGORIES: Record<string, TranslationString> = {
  WORKSHOP:   { es: 'Talleres', en: 'Workshops' },
  CLEANUP:    { es: 'Limpiezas', en: 'Cleanups' },
  MARKET:     { es: 'Mercados', en: 'Markets' },
  CONCERT:    { es: 'Conciertos', en: 'Concerts' },
  SPORT:      { es: 'Deporte', en: 'Sports' },
  COMMUNITY:  { es: 'Comunidad', en: 'Community' },
  CULTURE:    { es: 'Cultura', en: 'Culture' },
  OTHER:      { es: 'Otros', en: 'Other' },
};

// ─────────────────────────────────────────────────────────────
// ARTICLE CATEGORIES
// ─────────────────────────────────────────────────────────────

export const ARTICLE_CATEGORIES: Record<string, TranslationString> = {
  ENVIRONMENT:    { es: 'Medio Ambiente', en: 'Environment' },
  COMMUNITY:      { es: 'Comunidad', en: 'Community' },
  BUSINESS:       { es: 'Negocios', en: 'Business' },
  SUSTAINABILITY: { es: 'Sostenibilidad', en: 'Sustainability' },
  TOURISM:        { es: 'Turismo', en: 'Tourism' },
  GENERAL:        { es: 'General', en: 'General' },
};

// ─────────────────────────────────────────────────────────────
// COMMUNITY STATS (demo data)
// ─────────────────────────────────────────────────────────────

export const DEMO_STATS = [
  { statKey: 'total_listings', statValue: 2847, statLabelEs: 'Anuncios publicados', statLabelEn: 'Published listings', icon: 'file-text' },
  { statKey: 'active_users', statValue: 1523, statLabelEs: 'Usuarios activos', statLabelEn: 'Active users', icon: 'users' },
  { statKey: 'kg_recycled', statValue: 48520, statLabelEs: 'Kg reciclados', statLabelEn: 'Kg recycled', icon: 'recycle' },
  { statKey: 'co2_saved', statValue: 12600, statLabelEs: 'Kg CO₂ ahorrados', statLabelEn: 'Kg CO₂ saved', icon: 'leaf' },
  { statKey: 'events_this_month', statValue: 34, statLabelEs: 'Eventos este mes', statLabelEn: 'Events this month', icon: 'calendar' },
  { statKey: 'businesses', statValue: 287, statLabelEs: 'Negocios locales', statLabelEn: 'Local businesses', icon: 'store' },
];
